name: http_requests
description:  HTTP Requests Package is inspired by the `Python Requests Module`, which is used to make HTTP requests and get responses. You can use it in your `Rest API`.
version: 3.1.0
homepage: https://github.com/sidhu-patil/http_requests
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0

flutter:
