name: http_requests
description:  HTTP Requests Package Inspired By Python Requests Module Which Is Used For To Make Http Request And Get Response. You Can Use It In Rest Api
version: 3.0.1
homepage: https://github.com/secanonm/http_requests
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0

flutter:
